name: Build Image
on:
  release:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "::set-env name=DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kbase/proto-ui
        build_args: BUILD_DATE=$DATE,VCS_REF=$GITHUB_SHA,BRANCH=$GITHUB_REF
        tags: $GITHUB_REF
